package battlezone.view;

import battlezone.controller.Venda_CRUD;
import battlezone.model.venda_model;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aline Buchino
 */
public class FrmCaixa extends javax.swing.JInternalFrame {

    /** Creates new form FrmCaixa */
    public FrmCaixa() {
        initComponents();
        setFrameIcon(new ImageIcon(this.getClass().getResource("/imagens/principal/LogoSemBorda.png")));
        
         tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Irá listar a tabela assim que iniciar a janela Produtos
         limparCampos();
    }
    
    public static String dataAtual(){
        Date data = new Date();
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/YYYY");
        return formatoData.format(data);
    }
    
    void limparCampos(){
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        total.setText("");
        recebido.setText("");
        total.setText("");
        troco.setText("");
        data.setText(dataAtual());
        Venda_CRUD.numeros();// consulta para que o código receba o novo valor
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        recebido = new app.bolivia.swing.JCTextField();
        data = new app.bolivia.swing.JCTextField();
        jLabelDATA = new javax.swing.JLabel();
        jLabelRECEBIDO = new javax.swing.JLabel();
        troco = new app.bolivia.swing.JCTextField();
        jLabelTROCO = new javax.swing.JLabel();
        produtos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        numeroVenda = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonCALCULO = new javax.swing.JButton();
        jButtonVENDA = new javax.swing.JButton();
        jButtonELIMINAR = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        tabelaProdutos = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        total = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("CAIXA");
        setPreferredSize(new java.awt.Dimension(1130, 555));

        desktopPane.setPreferredSize(new java.awt.Dimension(1130, 555));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/LogoSemBorda.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Praça das Bandeiras, N° 08 - Centro ");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("BATTLEZONE");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText(" São José do Rio Pardo - SP, 13720-000");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("(19) 3608-5465 / (19) 99890-5837");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(268, 268, 268))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMAÇÕES"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recebido.setBackground(new java.awt.Color(0, 128, 0));
        recebido.setBorder(null);
        recebido.setForeground(new java.awt.Color(255, 255, 255));
        recebido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recebido.setOpaque(false);
        recebido.setPhColor(new java.awt.Color(255, 255, 255));
        recebido.setPlaceholder("RECEBIDO");
        jPanel3.add(recebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 130, 40));

        data.setEditable(false);
        data.setBackground(new java.awt.Color(0, 128, 0));
        data.setBorder(null);
        data.setForeground(new java.awt.Color(255, 255, 255));
        data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        data.setOpaque(false);
        data.setPhColor(new java.awt.Color(255, 255, 255));
        data.setPlaceholder("DATA");
        jPanel3.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 180, 40));

        jLabelDATA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/data.png"))); // NOI18N
        jPanel3.add(jLabelDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 24, -1, -1));

        jLabelRECEBIDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/recibido.png"))); // NOI18N
        jPanel3.add(jLabelRECEBIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 24, -1, -1));

        troco.setBackground(new java.awt.Color(0, 128, 0));
        troco.setBorder(null);
        troco.setForeground(new java.awt.Color(255, 255, 255));
        troco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        troco.setOpaque(false);
        troco.setPhColor(new java.awt.Color(255, 255, 255));
        troco.setPlaceholder("TROCO");
        jPanel3.add(troco, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 140, 40));

        jLabelTROCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/troco.png"))); // NOI18N
        jPanel3.add(jLabelTROCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 24, -1, -1));

        produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/produtos.png"))); // NOI18N
        produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        produtos.setPreferredSize(new java.awt.Dimension(50, 40));
        produtos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/produtos1.png"))); // NOI18N
        produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosActionPerformed(evt);
            }
        });
        jPanel3.add(produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 127, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 170, 835, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numeroVenda.setEditable(false);
        numeroVenda.setBackground(new java.awt.Color(0, 128, 0));
        numeroVenda.setBorder(null);
        numeroVenda.setForeground(new java.awt.Color(255, 255, 255));
        numeroVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numeroVenda.setOpaque(false);
        numeroVenda.setPhColor(new java.awt.Color(255, 255, 255));
        numeroVenda.setPlaceholder("FATURA");
        jPanel4.add(numeroVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NÚMERO DA VENDA");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/numFac.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 0, 242, 140));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButtonCALCULO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/calculo.png"))); // NOI18N
        jButtonCALCULO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCALCULO.setOpaque(false);
        jButtonCALCULO.setPreferredSize(new java.awt.Dimension(195, 50));
        jButtonCALCULO.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/calculo1.png"))); // NOI18N
        jButtonCALCULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCALCULOActionPerformed(evt);
            }
        });

        jButtonVENDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/venda.png"))); // NOI18N
        jButtonVENDA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVENDA.setPreferredSize(new java.awt.Dimension(195, 50));
        jButtonVENDA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/venda1.png"))); // NOI18N
        jButtonVENDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVENDAActionPerformed(evt);
            }
        });

        jButtonELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/elimina.png"))); // NOI18N
        jButtonELIMINAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonELIMINAR.setPreferredSize(new java.awt.Dimension(195, 50));
        jButtonELIMINAR.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/elimina1.png"))); // NOI18N
        jButtonELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonELIMINARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCALCULO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButtonCALCULO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButtonVENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 170, 240, 340));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "TIPO PROD / SERV", "DESCRIÇÃO", "VALOR", "QUANTIDADE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setViewportView(tabela);

        scrollPane1.add(tabelaProdutos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 278, 835, -1));

        total.setBackground(new java.awt.Color(0, 128, 0));
        total.setBorder(null);
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.setOpaque(false);
        total.setPhColor(new java.awt.Color(255, 255, 255));
        total.setPlaceholder("TOTAL");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa/total.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, -1, -1));

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    FrmListaProd listaProd;
    private void produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosActionPerformed
        if(listaProd == null){
          listaProd = new FrmListaProd();
      }
      desktopPane.add(listaProd);
      listaProd.setVisible(true);
      listaProd.setLocation(140, 35);
    }//GEN-LAST:event_produtosActionPerformed

    private void jButtonCALCULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCALCULOActionPerformed
        if (tabela.getRowCount() < 1){ // se não houver valor
            JOptionPane.showMessageDialog(this, "Operação não realizada", "ERRO", 0);
        }else if(recebido.getText().equals("")){ // se o valor recebido nulo
            JOptionPane.showMessageDialog(this, "Insira um valor recebido", "Cobrança", 0,
            new ImageIcon (getClass().getResource("/imagens/principal/info.png")));
        }else{ // se houver um valor válido irá receber e guardar na variável "recebi e tot" do tipo Double
            double recebi = Double.parseDouble(recebido.getText());
            double tot = Double.parseDouble(total.getText());
            
            if (recebi < tot){ 
                JOptionPane.showMessageDialog(this, "Valor Inválido, INFERIOR", "Cobrança", 0,
                new ImageIcon (getClass().getResource("/imagens/principal/info.png")));
            } else{
                this.troco.setText(String.valueOf(recebi - tot));
            }
        }
    }//GEN-LAST:event_jButtonCALCULOActionPerformed

    private void jButtonVENDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVENDAActionPerformed
        if (tabela.getRowCount() < 1){
            JOptionPane.showMessageDialog(this, "Impossível realizar a venda", "ERRO", 0);
        }else{
            venda_model v = new venda_model(); // irá acessar a classe de venda_model
            v.setPrimaryKey(numeroVenda.getText()); // a chave primária irá receber o numeroVenda
            v.setTotal(total.getText()); // o total irá receber o que estiver no campo total
            v.setData(data.getText()); // e a data o que estiver no campo data
            int opc = Venda_CRUD.registrarVenda(v); // irá passar todos os valores recebidos para registra no BD
            if (opc != 0){ // significa que registrou
                limparCampos();
                JOptionPane.showMessageDialog(this, "Venda efetuada", "Venda", 0,
                new ImageIcon (getClass().getResource("/imagens/principal/info.png")));       
            }
        }
    }//GEN-LAST:event_jButtonVENDAActionPerformed

    private void jButtonELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonELIMINARActionPerformed
        if (tabela.getRowCount() > 0){ // se houver algum irá armazenar a informação dentro da variável modelo
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            int linha = tabela.getSelectedRow();
            if (linha >= 0){
                modelo.removeRow(linha);
                FrmListaProd lp = new FrmListaProd();
                lp.calcular(); // associa novamente para poder recalcular o total quando algum produto for excluido
            }else{
                JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir", "Exclusão", 0,
                new ImageIcon (getClass().getResource("/imagens/principal/info.png")));   
            }
        }else{
            JOptionPane.showMessageDialog(this, "Não há registro para excluir", "Exclusão", 0,
            new ImageIcon (getClass().getResource("/imagens/principal/info.png"))); 
        }
    }//GEN-LAST:event_jButtonELIMINARActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField data;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCALCULO;
    private javax.swing.JButton jButtonELIMINAR;
    private javax.swing.JButton jButtonVENDA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDATA;
    private javax.swing.JLabel jLabelRECEBIDO;
    private javax.swing.JLabel jLabelTROCO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static app.bolivia.swing.JCTextField numeroVenda;
    private javax.swing.JButton produtos;
    public static app.bolivia.swing.JCTextField recebido;
    private java.awt.ScrollPane scrollPane1;
    public static javax.swing.JTable tabela;
    private javax.swing.JScrollPane tabelaProdutos;
    public static app.bolivia.swing.JCTextField total;
    public static app.bolivia.swing.JCTextField troco;
    // End of variables declaration//GEN-END:variables

}
