package battlezone.view;

import battlezone.controller.ListaProd_CRUD;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuário 2
 */
public class FrmListaProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaProd
     */
    public FrmListaProd() {
        initComponents();
        setFrameIcon(new ImageIcon(this.getClass().getResource("/imagens/principal/LogoSemBorda.png")));
        
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Irá listar a tabela assim que iniciar a janela 
        ListaProd_CRUD.listarCat("");
        
        tipo.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent ie){
                
                if(tipo.getSelectedIndex() == 0){
                    ListaProd_CRUD.listarCat(tipo.getSelectedItem().toString());
                }
                if(tipo.getSelectedIndex() == 1){
                    ListaProd_CRUD.listarCat(tipo.getSelectedItem().toString());
                }
                if(tipo.getSelectedIndex() == 2){
                    ListaProd_CRUD.listarCat(tipo.getSelectedItem().toString());
                }
                if(tipo.getSelectedIndex() == 3){
                    ListaProd_CRUD.listarCat(tipo.getSelectedItem().toString());
                }
                if(tipo.getSelectedIndex() == 4){
                    ListaProd_CRUD.listarCat(tipo.getSelectedItem().toString());
                }
                if(tipo.getSelectedIndex() == 5){
                    ListaProd_CRUD.listarCat(tipo.getSelectedItem().toString());
                }
            
            }
       
         });
        
    }
    
    public void calcular(){
        String pre;
        String quan;
        double total = 0;
        double preco;
        int quantidade;
        double  calc = 0.0;
        
        for(int i = 0; i < FrmCaixa.tabela.getRowCount(); i++){ // percorrer todos os items do formulário vendas para verificar as quantidades e ir totalizando
            pre = FrmCaixa.tabela.getValueAt(i, 3).toString(); // recebe o preço do formulário Caixa, no campo o campo 4
            quan = FrmCaixa.tabela.getValueAt(i, 4).toString(); // recebe a quantidade do formulário Caixa
            preco = Double.parseDouble(pre); // guardará os valores do campo pre convertendo para Double
            quantidade = Integer.parseInt(quan); // guardará a quantidade do campo quan sendo todos inteiros
            calc = preco * quantidade; // faz o cáculo 
            total = total + calc; // faz o cálculo do total referente a quantidade que for adquirida
            FrmCaixa.tabela.setValueAt(Math.rint(calc * 100) / 100, i, 5); // está passando um valor na possição 5, ou seja, no TOTAL. E o cáculo é p/ dar uma quebra nos números, como 0,00.
        }
        FrmCaixa.total.setText("" + Math.rint(total * 100) / 100);// pegará o texto e mostrará de forma arredondada (Math.rint)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buscar = new app.bolivia.swing.JCTextField();
        nomeProd = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setClosable(true);
        setTitle("LISTA DE PRODUTOS E SERVIÇOS");
        setPreferredSize(new java.awt.Dimension(800, 480));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        buscar.setBackground(new java.awt.Color(15, 164, 57));
        buscar.setBorder(null);
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setOpaque(false);
        buscar.setPhColor(new java.awt.Color(255, 255, 255));
        buscar.setPlaceholder("CÓDIGO / NOME");
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        nomeProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/buscarL.png"))); // NOI18N

        tipo.setBackground(new java.awt.Color(0, 102, 0));
        tipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tipo.setForeground(new java.awt.Color(255, 255, 255));
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE PRODUTO", "INFORMATICA", "ELETRONICA", "PAPELARIA", "ASSISTENCIA", "ESCRITORIO" }));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/tipoprodutos1.png"))); // NOI18N

        registrar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/registrar.png"))); // NOI18N
        registrar.setText("ENVIAR ");
        registrar.setBorder(null);
        registrar.setContentAreaFilled(false);
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrar.setPreferredSize(new java.awt.Dimension(73, 95));
        registrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/registrar1.png"))); // NOI18N
        registrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeProd))
                .addGap(52, 52, 52)
                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nomeProd)))))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMAÇÕES "));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "TIPO", "NOME PROD / SERV", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
         buscar.setText(buscar.getText().toUpperCase()); // deixar tudo maiusculo
         ListaProd_CRUD.listarCat(buscar.getText()); // listar Produtos do BD
    }//GEN-LAST:event_buscarKeyReleased

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        if (tabela.getRowCount() > 0){ // verifica se a tabela há algum registro
            try{
                String quant = null;
                DefaultTableModel tabeladet = (DefaultTableModel) FrmCaixa.tabela.getModel(); // referencia a tabela do formulário caixa criando o objeto tabeladet
                
                String[] dado = new String[6]; // armazena as informações dos 6 campos
                
                int linha = tabela.getSelectedRow(); // variável linha para verificar cada linha selecionada
                
                if(linha == -1){ // se não tiver linha selecionada
                    JOptionPane.showMessageDialog(this, "Selecione um produto", "Produtos", 0,
                    new ImageIcon (getClass().getResource("/imagens/principal/info.png")));
                }else{
                    String cod = tabela.getValueAt(linha, 0).toString(); // recebe o que tiver na 1° posição da tabela
                    String tipo = tabela.getValueAt(linha, 1).toString();
                    String nom = tabela.getValueAt(linha, 2).toString();
                    String preco = tabela.getValueAt(linha, 3).toString();
                    int c = 0; // irá passar as informações e valores
                    int j = 0;
                    
                    // o showInputDialog aceita o recebimento de valores
                    
                    quant = JOptionPane.showInputDialog(this, "Quantidade", "Produtos", JOptionPane.INFORMATION_MESSAGE); //mostrará a quantidade dos produtos
                    while (!ListaProd_CRUD.isNumber(quant) && quant != null){ // Verifica se não está passando um valor numérico ou se o valor numérico é nulo
                        quant = JOptionPane.showInputDialog(this, "Somente valores numéricos maiores que 0:",
                                JOptionPane.ERROR_MESSAGE);
                    }
                    if((quant.equals("")) || (quant.equals("0"))){
                        JOptionPane.showMessageDialog(this, "Insira um valor maior que 0", "Produtos", 0,
                        new ImageIcon (getClass().getResource("/imagens/principal/info.png")));
                    }else{
                        for (int i = 0; i < FrmCaixa.tabela.getRowCount(); i++){
                            Object com = FrmCaixa.tabela.getValueAt(i, 0); // Guarda as informações da 1° posição (código)
                            Object quant1 = FrmCaixa.tabela.getValueAt(i, 4); // guarda as informações da 4° posição (quantidade)
                            if(cod.equals(com)){ // verifica se o código do FrmListaProd é o mesmo que foi enviado ao FrmCaixa
                                j = i; // servirá como a posição dos objetos na tabela
                                int quantT = Integer.parseInt(quant) + Integer.parseInt((String) quant1); // pega a quant anterior (que já havia add) e soma com a nova (que está add no momento)
                                FrmCaixa.tabela.setValueAt(String.valueOf(quantT), i, 4); // aplica a quantidade total no campo 4
                                c++; // irá incrementar para passar pro próximo
                                calcular(); // efetuará o cálculo no método que foi criado
                                FrmCaixa.recebido.setText(""); // os campos são zerados p/ digitar o valor recebido e verificar o calculo que será feito
                                FrmCaixa.troco.setText("");
                            }
                        }
                        if (c == 0){ // o contador irá receber valores de acordo com as posições
                            
                            dado[0] = cod;
                            dado[1] = tipo;
                            dado[2] = nom;
                            dado[3] = preco;
                            dado[4] = quant;
                            
                            tabeladet.addRow(dado); // irá ser adicionado na tabela referente a tabela Caixa
                            
                            FrmCaixa.tabela.setModel(tabeladet); // passará as informações para a tabela
                            calcular(); // irá recalcular
                            
                            FrmCaixa.recebido.setText(""); // limpar novamente os campos
                            FrmCaixa.troco.setText("");
                        }
                    }
                }
            }catch (Exception e){ 
            }
        }else{
            JOptionPane.showMessageDialog(this, "Não há registros", "Produtos", 0,
            new ImageIcon (getClass().getResource("/imagens/principal/info.png")));
        }
    }//GEN-LAST:event_registrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField buscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeProd;
    private javax.swing.JButton registrar;
    public static javax.swing.JTable tabela;
    public static javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
