package battlezone.view;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Aline Buchino
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public boolean fecharJanela(Object obj){
        
        JInternalFrame[] ativo = desktopPane.getAllFrames();
        boolean fechado = true;
        int i = 0;
        while (i < ativo.length && fechado){
            if(ativo[i] == obj){
                fechado = false;            
            }
            i++;
        }
        return fechado;
    }
    
    class horas implements ActionListener{
        
        public void actionPerformed (ActionEvent e){
            Date sistemaHora = new Date();
            String pmAm = "HH:mm:ss"; 
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            hora.setText(String.format(formato.format(sistemaHora), now));
        }
    }

    public MenuPrincipal() {
        initComponents();
        URL caminhoIcone = getClass().getResource("/imagens/principal/LogoSemBorda.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        setExtendedState(MAXIMIZED_BOTH); 
             
    }
    
  battlezone.view.FrmUsuarios tela;
  private void UsuariosInternalFrame() {
      
      if(fecharJanela(tela)){
          tela = new FrmUsuarios();
          desktopPane.add(tela).setLocation(490,140);
          tela.show();
      } else{
          tela.toFront();
          tela.show();
      }     
  }
  
  battlezone.view.FrmProdutos tela1;
  private void ProdutosInternalFrame() {
       if(fecharJanela(tela1)){
          tela1 = new FrmProdutos();
          desktopPane.add(tela1).setLocation(490,140);
          tela1.show();
      } else{
          tela1.toFront();
          tela1.show();
      }
  }
  
  battlezone.view.FrmVendas tela2;
  private void VendasInternalFrame(){
       if(fecharJanela(tela1)){
          tela2 = new FrmVendas();
          desktopPane.add(tela2).setLocation(490,140);
          tela2.show();
      } else{
          tela2.toFront();
          tela2.show();
      }
  }
    
  battlezone.view.FrmCaixa tela3;
  private void CaixaInternalFrame(){
       if(fecharJanela(tela3)){
          tela3 = new FrmCaixa();
          desktopPane.add(tela3).setLocation(280,140);
          tela3.show();
      } else{
          tela3.toFront();
          tela3.show();
      }
  }
  
  battlezone.view.FrmInformacoes tela4;
  private void InformacoesInternalFrame(){
       if(fecharJanela(tela4)){
          tela4 = new FrmInformacoes();
          desktopPane.add(tela4).setLocation(280,80);
          tela4.show();
      } else{
          tela4.toFront();
          tela4.show();
      }
  }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hora = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        logoConect = new javax.swing.JLabel();
        userConect = new javax.swing.JLabel();
        logoDesconect = new javax.swing.JLabel();
        userDesconect = new javax.swing.JLabel();
        buttonUsuarios = new javax.swing.JButton();
        buttonProdutos = new javax.swing.JButton();
        buttonVendas = new javax.swing.JButton();
        buttonCaixa = new javax.swing.JButton();
        buttonInformacoes = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo a Battle Zone");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelPrincipal.setPreferredSize(new java.awt.Dimension(1200, 1280));
        painelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 790));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hora.setBackground(new java.awt.Color(240, 240, 240));
        hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 255, 255));
        hora.setText("HORA");
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 20));

        data.setBackground(new java.awt.Color(255, 255, 255));
        data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        data.setForeground(new java.awt.Color(255, 255, 255));
        data.setText("DIA - MÊS - ANO");
        data.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        logoConect.setBackground(new java.awt.Color(255, 255, 255));
        logoConect.setForeground(new java.awt.Color(255, 255, 255));
        logoConect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/conectado.png"))); // NOI18N
        jPanel1.add(logoConect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        userConect.setBackground(new java.awt.Color(255, 255, 255));
        userConect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userConect.setForeground(new java.awt.Color(255, 255, 255));
        userConect.setText("USUÁRIO");
        jPanel1.add(userConect, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        logoDesconect.setBackground(new java.awt.Color(255, 255, 255));
        logoDesconect.setForeground(new java.awt.Color(255, 255, 255));
        logoDesconect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/desconec.png"))); // NOI18N
        jPanel1.add(logoDesconect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        userDesconect.setBackground(new java.awt.Color(255, 255, 255));
        userDesconect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userDesconect.setForeground(new java.awt.Color(255, 255, 255));
        userDesconect.setText("DESCONECTAR");
        userDesconect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userDesconect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDesconectMouseClicked(evt);
            }
        });
        jPanel1.add(userDesconect, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        buttonUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        buttonUsuarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        buttonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario.png"))); // NOI18N
        buttonUsuarios.setText("USUÁRIOS");
        buttonUsuarios.setContentAreaFilled(false);
        buttonUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonUsuarios.setPreferredSize(new java.awt.Dimension(100, 88));
        buttonUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario2.png"))); // NOI18N
        buttonUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(buttonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 110));

        buttonProdutos.setBackground(new java.awt.Color(255, 255, 255));
        buttonProdutos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonProdutos.setForeground(new java.awt.Color(255, 255, 255));
        buttonProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos.png"))); // NOI18N
        buttonProdutos.setText("PRODUTOS");
        buttonProdutos.setContentAreaFilled(false);
        buttonProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonProdutos.setPreferredSize(new java.awt.Dimension(100, 88));
        buttonProdutos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos2.png"))); // NOI18N
        buttonProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(buttonProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 110));

        buttonVendas.setBackground(new java.awt.Color(255, 255, 255));
        buttonVendas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonVendas.setForeground(new java.awt.Color(255, 255, 255));
        buttonVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/vendas.png"))); // NOI18N
        buttonVendas.setText("VENDAS");
        buttonVendas.setContentAreaFilled(false);
        buttonVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonVendas.setPreferredSize(new java.awt.Dimension(100, 88));
        buttonVendas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/vendas2.png"))); // NOI18N
        buttonVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVendasActionPerformed(evt);
            }
        });
        jPanel1.add(buttonVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, 110));

        buttonCaixa.setBackground(new java.awt.Color(255, 255, 255));
        buttonCaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCaixa.setForeground(new java.awt.Color(255, 255, 255));
        buttonCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/caixa.png"))); // NOI18N
        buttonCaixa.setText("CAIXA");
        buttonCaixa.setContentAreaFilled(false);
        buttonCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCaixa.setPreferredSize(new java.awt.Dimension(100, 88));
        buttonCaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/caixa2.png"))); // NOI18N
        buttonCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, 110));

        buttonInformacoes.setBackground(new java.awt.Color(255, 255, 255));
        buttonInformacoes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonInformacoes.setForeground(new java.awt.Color(255, 255, 255));
        buttonInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/info.png"))); // NOI18N
        buttonInformacoes.setText("INFO");
        buttonInformacoes.setContentAreaFilled(false);
        buttonInformacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonInformacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonInformacoes.setPreferredSize(new java.awt.Dimension(100, 88));
        buttonInformacoes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/info2.png"))); // NOI18N
        buttonInformacoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInformacoesActionPerformed(evt);
            }
        });
        jPanel1.add(buttonInformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, -1, 110));

        desktopPane.setOpaque(false);
        desktopPane.setPreferredSize(new java.awt.Dimension(1280, 790));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/TelaPrincipal².png"))); // NOI18N

        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addContainerGap(2, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 1420, 820));

        painelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsuariosActionPerformed
         UsuariosInternalFrame();
    }//GEN-LAST:event_buttonUsuariosActionPerformed

    private void buttonProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProdutosActionPerformed
        ProdutosInternalFrame();
    }//GEN-LAST:event_buttonProdutosActionPerformed

    private void buttonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVendasActionPerformed
        VendasInternalFrame();
    }//GEN-LAST:event_buttonVendasActionPerformed

    private void buttonCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCaixaActionPerformed
        CaixaInternalFrame();
    }//GEN-LAST:event_buttonCaixaActionPerformed

    private void buttonInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInformacoesActionPerformed
        InformacoesInternalFrame();
    }//GEN-LAST:event_buttonInformacoesActionPerformed

    private void userDesconectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDesconectMouseClicked
        if (JOptionPane.showConfirmDialog(this, "Deseja fechar a sessão?", "Fechar sessão", JOptionPane.YES_NO_OPTION,0, 
            new ImageIcon (getClass().getResource("/imagens/principal/info.png"))) == JOptionPane.YES_OPTION) {
            this.dispose();
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);      
        }
    }//GEN-LAST:event_userDesconectMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Date sistemaData = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd MMMM YYYY");
        data.setText(formato.format(sistemaData));
        
        // Hora do sistema
        
        Timer hr = new Timer(100, new MenuPrincipal.horas());
        hr.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal menu = new MenuPrincipal();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCaixa;
    private javax.swing.JButton buttonInformacoes;
    private javax.swing.JButton buttonProdutos;
    private javax.swing.JButton buttonUsuarios;
    private javax.swing.JButton buttonVendas;
    private javax.swing.JLabel data;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoConect;
    private javax.swing.JLabel logoDesconect;
    private javax.swing.JPanel painelPrincipal;
    public javax.swing.JLabel userConect;
    private javax.swing.JLabel userDesconect;
    // End of variables declaration//GEN-END:variables

   
}
